# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rubish_qt_show.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again. Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
# from PyQt5.QtMultimediaWidgets import QVideoWidget
# from PyQt5.QtMultimedia import QMediaContent, QMediaPlayer


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        '''pushButton_1->open camera'''
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(70, 320, 201, 101))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setCheckable(False)
        self.pushButton_1.setAutoRepeat(False)
        self.pushButton_1.setAutoExclusive(False)
        self.pushButton_1.setAutoDefault(False)
        self.pushButton_1.setDefault(False)
        self.pushButton_1.setFlat(False)
        self.pushButton_1.setObjectName("pushButton_1")

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 320, 201, 101))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setAutoRepeat(False)
        self.pushButton_2.setAutoExclusive(False)
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setDefault(False)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        # self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        # self.radioButton_2.setGeometry(QtCore.QRect(310, 320, 201, 101))
        # font = QtGui.QFont()
        # font.setPointSize(18)
        # font.setBold(True)
        # font.setWeight(75)
        # self.radioButton_2.setFont(font)
        # self.radioButton_2.setChecked(False)
        # self.radioButton_2.setObjectName("radioButton_2")


        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(550, 320, 201, 101))
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")

        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(70, 440, 201, 101))
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")

        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(310, 450, 201, 101))
        self.pushButton_5.setObjectName("pushButton_5")

        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(550, 450, 201, 101))
        self.pushButton_6.setObjectName("pushButton_11")

        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(70, 40, 681, 271))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        # self.video_widget = QVideoWidget(self.centralwidget)
        # self.video_widget.resize(600, 600)
        # self.video_widget.setSizeIncrement(QtCore.QSize(841, 681))
        # self.horizontalLayout_2.addWidget(self.video_widget)
        # self.video_player = QMediaPlayer()
        # self.video_player.setMedia(QMediaContent(QtCore.QUrl.fromLocalFile("ry31a-kvnuq.avi")))
        # self.video_player.setVolume(40)
        # self.video_player.setVideoOutput(self.video_widget)

        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        # self.label.setSizeIncrement(QtCore.QSize(641, 481))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setLineWidth(3)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)

        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setLineWidth(3)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # self.label_3 = QtWidgets.QLabel(self.widget)
        # font = QtGui.QFont()
        # font.setPointSize(30)
        # font.setBold(True)
        # font.setItalic(True)
        # font.setWeight(75)
        # self.label_3.setFont(font)
        # self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        # self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        # self.label_3.setLineWidth(3)
        # self.label_3.setScaledContents(False)
        # self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        # self.label_3.setObjectName("label_2")
        # self.horizontalLayout_2.addWidget(self.label_3)
        # MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_1.setText(_translate("MainWindow", "打开摄像头"))
        self.pushButton_3.setText(_translate("MainWindow", "NONE"))
        self.pushButton_4.setText(_translate("MainWindow", "启动传送带和舵机"))
        self.pushButton_5.setText(_translate("MainWindow", "播放垃圾分类视频"))
        self.pushButton_6.setText(_translate("MainWindow", "拓展功能2"))
        self.pushButton_2.setText(_translate("MainWindow", "加载神经网络"))
        self.label.setText(_translate("MainWindow", "显示摄像头画面"))
        self.label_2.setText(_translate("MainWindow", "显示垃圾信息"))
        #  self.label_3.setText(_translate("MainWindow", "显示垃圾信息"))
